/**
 * FR-034/035: Internal transfer flow — 3 steps.
 *
 * Step 1 — Recipient: phone (+237…), account_id (UUID), or account_number (STD/PRJ/TDG…)
 * Step 2 — Select source account + enter amount (XAF → units × 100)
 * Step 3 — PIN confirmation: POST /auth/verify-pin → pin_token → POST /transactions/transfer
 *
 * FR-036: PIN token is single-use (60s TTL). Obtained immediately before submission.
 * Idempotency key is auto-generated by transactionsService.transfer().
 */
import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  TextInput,
  StyleSheet,
  SafeAreaView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../../App';
import { useTransfer } from '@/hooks/useTransactions';
import { useTotalBalance } from '@/hooks/useBalance';
import { PINKeypad } from '@/components/PINKeypad';
import { TerahButton } from '@/components/TerahButton';
import { TerahInput } from '@/components/TerahInput';
import { colors, spacing, radius } from '@/utils/tokens';
import { formatXAF } from '@/utils/formatXAF';
import { authService } from '@/services/auth';
import i18n from '@/locales';

type TransferNavProp = NativeStackNavigationProp<RootStackParamList, 'Transfer'>;

interface TransferScreenProps {
  navigation: TransferNavProp;
}

type Step = 1 | 2 | 3;

export default function TransferScreen({ navigation }: TransferScreenProps) {
  const [step, setStep] = useState<Step>(1);
  const [recipient, setRecipient] = useState('');
  const [recipientError, setRecipientError] = useState<string | null>(null);
  const [fromAccountId, setFromAccountId] = useState('');
  const [amountXAF, setAmountXAF] = useState('');
  const [amountError, setAmountError] = useState<string | null>(null);
  const [pin, setPin] = useState('');
  const [pinError, setPinError] = useState<string | null>(null);
  const [pinVerifying, setPinVerifying] = useState(false);

  const { accounts, isLoading: accountsLoading } = useTotalBalance();
  const { mutateAsync: transfer, isPending } = useTransfer();

  React.useEffect(() => {
    if (accounts && accounts.length > 0 && !fromAccountId) {
      setFromAccountId(accounts[0].account_id);
    }
  }, [accounts]);

  const fromAccount = accounts?.find((a) => a.account_id === fromAccountId);

  // ── Step 1: Recipient ──────────────────────────────────────────────────────

  const handleRecipientNext = () => {
    const trimmed = recipient.trim();
    if (!trimmed) {
      setRecipientError(i18n.t('transactions.recipient_required'));
      return;
    }
    setRecipientError(null);
    setStep(2);
  };

  // ── Step 2: Account + amount ───────────────────────────────────────────────

  const handleAmountNext = () => {
    const xaf = parseInt(amountXAF.replace(/\s/g, ''), 10);
    if (isNaN(xaf) || xaf <= 0) {
      setAmountError(i18n.t('transactions.amount_invalid'));
      return;
    }
    if (xaf < 1) {
      setAmountError(i18n.t('transactions.amount_too_low'));
      return;
    }
    setAmountError(null);
    setStep(3);
  };

  // ── Step 3: PIN + submit ───────────────────────────────────────────────────

  const handlePinKey = (key: string) => {
    if (key === 'backspace') {
      setPin((p) => p.slice(0, -1));
    } else if (pin.length < 6) {
      setPin((p) => p + key);
    }
    setPinError(null);
  };

  const handleSubmit = async () => {
    if (pin.length < 4) {
      setPinError(i18n.t('transactions.pin_error'));
      return;
    }

    setPinVerifying(true);
    setPinError(null);

    let pinToken: string;
    try {
      const res = await authService.verifyPin(pin);
      pinToken = res.pin_token;
    } catch {
      setPinError(i18n.t('transactions.pin_error'));
      setPinVerifying(false);
      setPin('');
      return;
    } finally {
      setPinVerifying(false);
    }

    const xaf = parseInt(amountXAF.replace(/\s/g, ''), 10);
    const amountUnits = xaf * 100;

    try {
      const txn = await transfer({
        from_account_id: fromAccountId,
        to_account_id: undefined,
        to_phone_or_account: recipient.trim(),
        amount: amountUnits,
        pin_token: pinToken,
      });
      navigation.replace('TransactionDetail', {
        transactionId: (txn as any).transaction_id ?? '',
        reference: (txn as any).reference,
      });
    } catch (err: any) {
      Alert.alert(
        i18n.t('transactions.transfer_failed'),
        err?.message ?? i18n.t('errors.generic'),
      );
    }
  };

  const renderHeader = (stepNum: Step) => (
    <View style={styles.header}>
      <TouchableOpacity
        onPress={() => (stepNum > 1 ? setStep((s) => (s - 1) as Step) : navigation.goBack())}
        style={styles.backButton}
        accessibilityRole="button"
        accessibilityLabel={i18n.t('common.back')}
        hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
      >
        <Text style={styles.backText}>← {i18n.t('common.back')}</Text>
      </TouchableOpacity>
      <Text style={styles.title}>{i18n.t('transactions.transfer_title')}</Text>
      <Text style={styles.stepIndicator}>
        {i18n.t('transactions.step_of', { step: stepNum, total: 3 })}
      </Text>
    </View>
  );

  // ── Step 1: Recipient input ────────────────────────────────────────────────
  if (step === 1) {
    return (
      <SafeAreaView style={styles.safe}>
        <ScrollView style={styles.screen} contentContainerStyle={styles.container}>
          {renderHeader(1)}
          <Text style={styles.sectionTitle}>
            {i18n.t('transactions.transfer_recipient_title')}
          </Text>

          <TerahInput
            label={i18n.t('transactions.transfer_recipient_label')}
            value={recipient}
            onChangeText={(t) => { setRecipient(t); setRecipientError(null); }}
            placeholder={i18n.t('transactions.transfer_recipient_placeholder')}
            hint={i18n.t('transactions.transfer_recipient_hint')}
            error={recipientError}
            autoCapitalize="none"
            autoCorrect={false}
            keyboardType="default"
          />

          <TerahButton
            label={i18n.t('common.continue')}
            onPress={handleRecipientNext}
            disabled={!recipient.trim()}
            style={styles.cta}
          />
        </ScrollView>
      </SafeAreaView>
    );
  }

  // ── Step 2: Account + amount ───────────────────────────────────────────────
  if (step === 2) {
    return (
      <SafeAreaView style={styles.safe}>
        <ScrollView style={styles.screen} contentContainerStyle={styles.container}>
          {renderHeader(2)}
          <Text style={styles.sectionTitle}>
            {i18n.t('transactions.transfer_amount_title')}
          </Text>

          {/* Source account selector */}
          <Text style={styles.fieldLabel}>{i18n.t('transactions.transfer_from_label')}</Text>
          {accountsLoading ? (
            <ActivityIndicator color={colors.teal} style={{ marginVertical: 16 }} />
          ) : (
            accounts?.map((acct) => (
              <TouchableOpacity
                key={acct.account_id}
                onPress={() => setFromAccountId(acct.account_id)}
                style={[
                  styles.accountOption,
                  fromAccountId === acct.account_id && styles.accountOptionSelected,
                ]}
                accessibilityRole="radio"
                accessibilityState={{ selected: fromAccountId === acct.account_id }}
              >
                <View style={{ flex: 1 }}>
                  <Text style={styles.accountName}>
                    {i18n.t(`accounts.${acct.account_type}`)}
                  </Text>
                  <Text style={styles.accountBalance}>{formatXAF(acct.balance)}</Text>
                </View>
                <View style={[
                  styles.radioCircle,
                  fromAccountId === acct.account_id && styles.radioCircleSelected,
                ]}>
                  {fromAccountId === acct.account_id && <View style={styles.radioDot} />}
                </View>
              </TouchableOpacity>
            ))
          )}

          {/* Amount input */}
          <Text style={[styles.fieldLabel, { marginTop: spacing.md }]}>
            {i18n.t('transactions.transfer_amount_label')}
          </Text>
          <View style={[styles.amountInputWrapper, amountError ? styles.inputError : null]}>
            <Text style={styles.currencyPrefix}>XAF</Text>
            <TextInput
              value={amountXAF}
              onChangeText={(t) => {
                setAmountXAF(t.replace(/[^0-9]/g, ''));
                setAmountError(null);
              }}
              keyboardType="numeric"
              placeholder={i18n.t('transactions.transfer_amount_placeholder')}
              placeholderTextColor={colors.midGrey}
              style={styles.amountInput}
              accessibilityLabel={i18n.t('transactions.transfer_amount_label')}
            />
          </View>
          {amountError ? (
            <Text style={styles.errorText}>{amountError}</Text>
          ) : (
            <Text style={styles.hintText}>{i18n.t('transactions.transfer_amount_hint')}</Text>
          )}

          <TerahButton
            label={i18n.t('common.continue')}
            onPress={handleAmountNext}
            disabled={!fromAccountId || !amountXAF}
            style={styles.cta}
          />
        </ScrollView>
      </SafeAreaView>
    );
  }

  // ── Step 3: PIN confirmation ───────────────────────────────────────────────
  const xaf = parseInt(amountXAF.replace(/\s/g, ''), 10) || 0;
  const isSubmitting = pinVerifying || isPending;

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView style={styles.screen} contentContainerStyle={styles.container}>
        {renderHeader(3)}

        {/* Summary */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>{i18n.t('transactions.transfer_confirm_to')}</Text>
            <Text style={styles.summaryValue} numberOfLines={1}>{recipient}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>{i18n.t('transactions.transfer_confirm_from')}</Text>
            <Text style={styles.summaryValue}>
              {fromAccount ? i18n.t(`accounts.${fromAccount.account_type}`) : '—'}
            </Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>{i18n.t('transactions.transfer_confirm_amount')}</Text>
            <Text style={[styles.summaryValue, styles.summaryAmount]}>
              {formatXAF(xaf * 100)}
            </Text>
          </View>
        </View>

        {/* PIN keypad */}
        <Text style={styles.pinTitle}>{i18n.t('transactions.transfer_pin_title')}</Text>
        <Text style={styles.pinSubtitle}>{i18n.t('transactions.transfer_pin_subtitle')}</Text>

        {/* PIN dots */}
        <View style={styles.pinDots} accessibilityLabel={`${pin.length} chiffres saisis`}>
          {[0, 1, 2, 3, 4, 5].map((i) => (
            <View
              key={i}
              style={[styles.pinDot, i < pin.length && styles.pinDotFilled]}
            />
          ))}
        </View>

        {pinError ? (
          <Text style={styles.pinError}>{pinError}</Text>
        ) : null}

        <PINKeypad
          onKeyPress={handlePinKey}
          disabled={isSubmitting}
          style={styles.keypad}
        />

        <TerahButton
          label={
            isSubmitting
              ? i18n.t('transactions.pin_verifying')
              : i18n.t('transactions.transfer_submit')
          }
          onPress={handleSubmit}
          loading={isSubmitting}
          disabled={pin.length < 4 || isSubmitting}
          style={styles.cta}
        />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.offWhite },
  screen: { flex: 1, backgroundColor: colors.offWhite },
  container: { paddingHorizontal: spacing.md, paddingBottom: 40 },
  header: { paddingTop: spacing.lg, paddingBottom: spacing.md },
  backButton: { minHeight: 44, alignSelf: 'flex-start', justifyContent: 'center', marginBottom: spacing.sm },
  backText: { fontFamily: 'Roboto_500Medium', fontSize: 14, color: colors.teal },
  title: { fontFamily: 'Poppins_700Bold', fontSize: 24, color: colors.navy, marginBottom: 4 },
  stepIndicator: { fontFamily: 'Roboto_400Regular', fontSize: 12, color: colors.midGrey },
  sectionTitle: { fontFamily: 'Poppins_600SemiBold', fontSize: 16, color: colors.navy, marginBottom: spacing.md },
  fieldLabel: { fontFamily: 'Roboto_500Medium', fontSize: 14, color: colors.darkGrey, marginBottom: spacing.sm },
  accountOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  accountOptionSelected: { borderColor: colors.teal },
  accountName: { fontFamily: 'Poppins_600SemiBold', fontSize: 14, color: colors.navy },
  accountBalance: { fontFamily: 'Roboto_400Regular', fontSize: 13, color: colors.midGrey, marginTop: 2 },
  radioCircle: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: colors.lightGrey, alignItems: 'center', justifyContent: 'center' },
  radioCircleSelected: { borderColor: colors.teal },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.teal },
  amountInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.lightGrey,
    paddingHorizontal: spacing.md,
    height: 56,
    marginBottom: 4,
  },
  inputError: { borderColor: colors.error },
  currencyPrefix: { fontFamily: 'Poppins_600SemiBold', fontSize: 16, color: colors.navy, marginRight: 10 },
  amountInput: { flex: 1, fontFamily: 'Roboto_400Regular', fontSize: 20, color: colors.darkGrey, paddingVertical: 0 },
  hintText: { fontFamily: 'Roboto_400Regular', fontSize: 12, color: colors.midGrey, marginBottom: spacing.md },
  errorText: { fontFamily: 'Roboto_400Regular', fontSize: 12, color: colors.error, marginBottom: spacing.md },
  summaryCard: {
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
  },
  summaryKey: { fontFamily: 'Roboto_400Regular', fontSize: 14, color: colors.midGrey, flex: 1 },
  summaryValue: { fontFamily: 'Roboto_500Medium', fontSize: 14, color: colors.darkGrey, flex: 2, textAlign: 'right' },
  summaryAmount: { fontFamily: 'Poppins_700Bold', fontSize: 18, color: colors.navy },
  pinTitle: { fontFamily: 'Poppins_600SemiBold', fontSize: 16, color: colors.navy, textAlign: 'center', marginBottom: 4 },
  pinSubtitle: { fontFamily: 'Roboto_400Regular', fontSize: 13, color: colors.midGrey, textAlign: 'center', marginBottom: spacing.lg },
  pinDots: { flexDirection: 'row', justifyContent: 'center', gap: 16, marginBottom: spacing.sm },
  pinDot: { width: 16, height: 16, borderRadius: 8, borderWidth: 2, borderColor: colors.lightGrey, backgroundColor: 'transparent' },
  pinDotFilled: { backgroundColor: colors.navy, borderColor: colors.navy },
  pinError: { fontFamily: 'Roboto_400Regular', fontSize: 13, color: colors.error, textAlign: 'center', marginBottom: spacing.sm },
  keypad: { marginBottom: spacing.lg },
  cta: { marginTop: spacing.md },
});
